// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpflsxdvvvajzkiyuiur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wZmxzeGR2dnZhanpraXl1aXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjYxOTMsImV4cCI6MjA2NjI0MjE5M30.VGrCegpOs3y0xAsiL0uQuax6eGwdAQWxxW0YGWitxI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);